# This is a basic workflow we will use in this demo

name: demo-gitops
permissions:
  id-token: write # required to use OIDC authentication
  contents: write # required
  actions: read
  security-events: write
  statuses: write

on:
  push:
    branches: [ main ]
env:
  NCR_REPOSITORY: ybhan-test-ncr

jobs:
  build:
    name: Build and Pushing the Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to NCR
      id: login-ncr
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.NCR_CONTAINER_REGISTRY }}
        username: ${{ secrets.NCR_ACCESS_KEY }}
        password: ${{ secrets.NCR_SECRET_KEY }}

    - name: Build and push image
      id: build-image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.NCR_CONTAINER_REGISTRY }}/tag-name:latest
